version: "3"

volumes:
  dtm_db_data:


services:
  web:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    restart: always
    ports:
      - 8002:8000
    volumes:
      - ./src/backend:/project/src/backend
    env_file: .env
    networks:
      - dtm-network
    container_name: api

  db:
    image: postgis/postgis:14-3.4-alpine
    restart: always
    volumes:
      - dtm_db_data:/var/lib/postgresql/data/
    env_file: .env
    networks:
      - dtm-network
    container_name: db

networks:
  dtm-network:
    name: dtm-network