[project]
name = "DTM"
version = "0.1.0"
description = "Drone Tasking Manager"
authors = [
    {name = "HOTOSM", email = "sysadmin@hotosm.org"},
]
dependencies = [
    "fastapi==0.104.1",
    "geojson==3.1.0",
    "uvicorn==0.24.0",
    "pydantic==2.5.2",
    "pydantic-settings==2.1.0",
    "geojson-pydantic==1.0.1",
    "python-dotenv==1.0.0",
    "ipython==8.14.0",
    "werkzeug==3.0.1",
    "python-jose[cryptography]==3.3.0",
    "shapely==2.0.2",
    "sqlalchemy==2.0.23",
    "SQLAlchemy-Utils==0.41.1",
    "geoalchemy2==0.14.2",
    "psycopg2>=2.9.9",
    "requests>=2.32.3",
    "loguru>=0.7.2",
    "python-multipart>=0.0.9",
    "fmtm-splitter>=1.2.1",
]
requires-python = ">=3.10"
license = {text = "GPL-3.0-only"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
